version: "3.7"

services: 

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: shop-system
    container_name: shop_system-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - shop-system

  db:
    image: mysql:5.7
    container_name: shop_system-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shop-system
      MYSQL_ROOT_PASSWORD: j/W5Lyg#]/>d#
      MYSQL_PASSWORD: j/W5Lyg#]/>d#
      MYSQL_USER: manager
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
        - 3376:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - shop-system

  nginx:
    image: nginx:1.17-alpine
    container_name: shop_system-nginx
    restart: unless-stopped
    ports: 
      - 8078:80
    volumes: 
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks: 
      - shop-system

networks: 
  shop-system:
    driver: bridge